source 'https://rubygems.org'

gem 'appium_capybara'
gem 'capybara'
gem 'capybara-screenshot'
gem 'chromedriver-helper'
gem 'cucumber'
gem 'hash'
gem 'json'
gem 'loofah'
gem 'parallel_tests', group: :development
gem 'peach'
gem 'report_builder'
gem 'rubocop'
gem 'selenium-webdriver'
gem 'site_prism'
gem 'rspec'
